SELECT
	U.USER_ID AS SELLER_ID,
	U.USER_NAME AS SELLER_NAME,
	U.USER_SNAME AS SELLER_SNAME,
	COUNT(R.REVIEW_ID) AS NUMBER_OF_REVIEWED,
	ROUND(AVG(R.STARS), 2) AS AVERAGE_STARS
FROM
	REVIEW R
	JOIN PRODUCT P ON P.PRODUCT_ID = R.PRODUCT_ID
	JOIN SELLER S ON S.SELLER_ID = P.SELLER_ID
	JOIN USERS U ON U.USER_ID = S.SELLER_ID
GROUP BY
	U.USER_ID,
	U.USER_NAME,
	U.USER_SNAME
ORDER BY
	AVERAGE_STARS DESC,
	NUMBER_OF_REVIEWED DESC,
	U.USER_ID ASC