CREATE TABLE USERS (
	USER_ID INTEGER NOT NULL,
	USER_NAME VARCHAR(30) NOT NULL,
	USER_SNAME VARCHAR(30) NOT NULL,
	GENDER VARCHAR(1) NOT NULL,
	USER_EMAIL VARCHAR(72) NOT NULL UNIQUE,
	DISTRICT VARCHAR(30) NOT NULL,
	PROVINCE VARCHAR(30) NOT NULL,
	POSTAL_CODE VARCHAR(5) NOT NULL,
	USER_TEL VARCHAR(11) NOT NULL,
	SELLER_FLAG BOOLEAN NOT NULL,
	CONSTRAINT USERS_PK PRIMARY KEY (USER_ID)
);

CREATE TABLE SELLER (
	SELLER_ID INTEGER NOT NULL,
	VERIFIED_STATUS BOOLEAN NOT NULL,
	CONSTRAINT SELLER_PK PRIMARY KEY (SELLER_ID),
	CONSTRAINT SELLER_ID_FK FOREIGN KEY (SELLER_ID) REFERENCES USERS (USER_ID)
);

CREATE TABLE SELLER_VERIFICATION_DOCS (
	ID_NUMBER INTEGER NOT NULL,
	SELLER_ID INTEGER NOT NULL,
	BANK_NAME VARCHAR(30) NOT NULL,
	BRANCH VARCHAR(30) NOT NULL,
	ACCOUNT_NUMBER VARCHAR(20) NOT NULL,
	TERM_ACCEPTION BOOLEAN NOT NULL,
	TAX_ADDRESS VARCHAR(100) NOT NULL,
	CONSTRAINT SELLER_VERIFICATION_DOCS_PK PRIMARY KEY (ID_NUMBER, SELLER_ID),
	CONSTRAINT SELLER_VERIFICATION_DOCS_FK FOREIGN KEY (SELLER_ID) REFERENCES SELLER (SELLER_ID)
);

CREATE TABLE COLLECTION (
	COLLECTION_ID INTEGER NOT NULL,
	COLLECTION_NAME VARCHAR(50) NOT NULL,
	ARTIST VARCHAR(30) NOT NULL,
	DETAIL VARCHAR(100) NOT NULL,
	CONSTRAINT COLLECTION_PK PRIMARY KEY (COLLECTION_ID)
);

CREATE TABLE ORDERS (
	ORDER_ID INTEGER NOT NULL,
	TOTAL_AMOUNT SMALLINT NOT NULL,
	ORDER_DATE_TIME TIMESTAMP NOT NULL,
	ORDER_STATUS VARCHAR(20) NOT NULL,
	TRANSACTION_METHOD VARCHAR(20) NOT NULL,
	TRANSACTION_STATUS VARCHAR(20) NOT NULL,
	BUYER_ID INTEGER NOT NULL,
	CONSTRAINT ORDER_PK PRIMARY KEY (ORDER_ID),
	CONSTRAINT ORDER_FK FOREIGN KEY (BUYER_ID) REFERENCES USERS (USER_ID)
);

CREATE TABLE PRODUCT (
	PRODUCT_ID INTEGER NOT NULL,
	SELLER_ID INTEGER NOT NULL,
	PRODUCT_NAME VARCHAR(60) NOT NULL,
	PRICE DECIMAL(9, 2) NOT NULL,
	DESCRIPTION VARCHAR(300) NOT NULL,
	IS_BOUGHT BOOLEAN NOT NULL,
	COLLECTION_ID INTEGER,
	ORDER_ID INTEGER,
	CONSTRAINT PRODUCT_PK PRIMARY KEY (PRODUCT_ID),
	CONSTRAINT SELLER_FK FOREIGN KEY (SELLER_ID) REFERENCES SELLER (SELLER_ID),
	CONSTRAINT COLLECTION_FK FOREIGN KEY (COLLECTION_ID) REFERENCES COLLECTION (COLLECTION_ID),
	CONSTRAINT ORDER_FK FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID)
);

CREATE TABLE REVIEW (
	REVIEW_ID INTEGER NOT NULL,
	PRODUCT_ID INTEGER NOT NULL,
	BUYER_ID INTEGER NOT NULL,
	REVIEW_CONTENT VARCHAR(100) NOT NULL,
	REVIEW_DATE_TIME TIMESTAMP NOT NULL,
	STARS SMALLINT NOT NULL,
	CONSTRAINT REVIEW_PK PRIMARY KEY (REVIEW_ID),
	CONSTRAINT REVIEW_FK2 FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID),
	CONSTRAINT REVIEW_FK FOREIGN KEY (BUYER_ID) REFERENCES USERS (USER_ID)
);

CREATE TABLE COMMENT (
	COMMENT_ID INTEGER NOT NULL,
	REVIEW_ID INTEGER NOT NULL,
	USER_ID INTEGER NOT NULL,
	COMMENT_CONTENT VARCHAR(100) NOT NULL,
	COMMENT_TIME TIMESTAMP NOT NULL,
	CONSTRAINT COMMENT_PK PRIMARY KEY (COMMENT_ID, REVIEW_ID),
	CONSTRAINT COMMENT_FK2 FOREIGN KEY (REVIEW_ID) REFERENCES REVIEW (REVIEW_ID),
	CONSTRAINT COMMENT_FK FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
);

CREATE TABLE ADMIN (
	ADMIN_ID INTEGER NOT NULL,
	EMAIL VARCHAR(72) NOT NULL,
	CONSTRAINT ADMIN_PK PRIMARY KEY (ADMIN_ID)
);

CREATE TABLE REPORT (
	REPORT_ID INTEGER NOT NULL,
	USER_ID INTEGER NOT NULL,
	TITLE VARCHAR(30) NOT NULL,
	CONTENT VARCHAR(100) NOT NULL,
	DATE_TIME TIMESTAMP NOT NULL,
	ADMIN_ID INTEGER NOT NULL,
	CONSTRAINT REPORT_PK PRIMARY KEY (REPORT_ID),
	CONSTRAINT REPORT_FK FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
	CONSTRAINT REPORT_FK2 FOREIGN KEY (ADMIN_ID) REFERENCES ADMIN (ADMIN_ID)
);

CREATE TABLE PRODUCT_PHOTOS (
	PRODUCT_ID INTEGER NOT NULL,
	PHOTO VARCHAR(2048) NOT NULL,
	CONSTRAINT PRODUCT_PHOTOS_PK PRIMARY KEY (PRODUCT_ID, PHOTO),
	CONSTRAINT PRODUCT_PHOTOS_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID)
);

CREATE TABLE PRODUCT_TAGS (
	PRODUCT_ID INTEGER NOT NULL,
	TAG VARCHAR(100) NOT NULL,
	CONSTRAINT PRODUCT_TAGS_PK PRIMARY KEY (PRODUCT_ID, TAG),
	CONSTRAINT PRODUCT_TAGS_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID)
);

CREATE TABLE CHAT_WITH (
	BUYER_ID INTEGER NOT NULL,
	SELLER_ID INTEGER NOT NULL,
	CONSTRAINT CHAT_WITH_PK PRIMARY KEY (BUYER_ID, SELLER_ID),
	CONSTRAINT CHAT_WITH_FK1 FOREIGN KEY (BUYER_ID) REFERENCES USERS (USER_ID),
	CONSTRAINT CHAT_WITH_FK2 FOREIGN KEY (SELLER_ID) REFERENCES USERS (USER_ID)
);

CREATE TABLE MESSAGE (
	MESSAGE_ID SERIAL NOT NULL,
	BUYER_ID INTEGER NOT NULL,
	SELLER_ID INTEGER NOT NULL,
	SENDER_ID INTEGER NOT NULL,
	MESSAGE_CONTENT VARCHAR(100) NOT NULL,
	IS_READ BOOLEAN NOT NULL,
	MESSAGE_DATE_TIME TIMESTAMP NOT NULL,
	CONSTRAINT MESSAGE_PK PRIMARY KEY (MESSAGE_ID, BUYER_ID, SELLER_ID),
	CONSTRAINT MESSAGE_FK FOREIGN KEY (BUYER_ID, SELLER_ID) REFERENCES CHAT_WITH (BUYER_ID, SELLER_ID)
);